# Configuration
APP_ROOT := $(abspath $(lastword $(MAKEFILE_LIST))/..)
APP_NAME := osprey
VENV?=/tmp/osprey-venv
PYTHON=${VENV}/bin/python3
PIP=${VENV}/bin/pip
export PIP_INDEX_URL=https://pypi.pacificclimate.org/simple

# Notebook targets
LOCAL_URL = http://localhost:5000
DEV_PORT ?= $(shell bash -c 'read -ep "Target port: " port; echo $$port')

# Used in target refresh-notebooks to make it looks like the notebooks have
# been refreshed from the production server below instead of from the local dev
# instance so the notebooks can also be used as tutorial notebooks.
OUTPUT_URL = https://docker-dev03.pcic.uvic.ca/wpsoutputs
SANITIZE_FILE := https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/raw/master/notebooks/output-sanitize.cfg


.PHONY: all
all: develop test-all clean-test test-notebooks-prod

.PHONY: help
help:
	@echo "Please use 'make <target>' where <target> is one of:"
	@echo "  help              to print this help message. (Default)"
	@echo "  install           to install app by running 'pip install -e .'"
	@echo "  develop           to install with additional development requirements."
	@echo "  start             to start $(APP_NAME) service as daemon (background process)."
	@echo "  stop              to stop $(APP_NAME) service."
	@echo "  restart           to restart $(APP_NAME) service."
	@echo "  status            to show status of $(APP_NAME) service."
	@echo "  clean             to remove all files generated by build and tests."
	@echo "\nTesting targets:"
	@echo "  test              to run tests (but skip long running tests)."
	@echo "  test-all          to run all tests (including long running tests)."
	@echo "  lint              to run code style checks with flake8."
	@echo "\nSphinx targets:"
	@echo "  docs              to generate HTML documentation with Sphinx."
	@echo "\nDeployment targets:"
	@echo "  dist              to build source and wheel package."

## Build targets

.PHONY: install
install: venv
	@echo "Installing application ..."
	@-bash -c '${PIP} install .'
	@echo "\nStart service with \`osprey start'"

.PHONY: develop
develop: venv
	@echo "Installing development requirements for tests and docs ..."
	@-bash -c '${PIP} install -e ".[dev]"'

.PHONY: start
start: venv
	@echo "Starting application ..."
	@-bash -c "${VENV}/bin/$(APP_NAME) start -d"

.PHONY: stop
stop: venv
	@echo "Stopping application ..."
	@-bash -c "${VENV}/bin/$(APP_NAME) stop"

.PHONY: restart
restart: venv stop start
	@echo "Restarting application ..."

.PHONY: status
status: venv
	@echo "Show status ..."
	@-bash -c "${VENV}/bin/$(APP_NAME) status"

.PHONY: clean
clean: clean-build clean-pyc clean-test # remove all build, test, coverage and Python artifacts

.PHONY: clean-build
clean-build:
	@echo "Remove build artifacts ..."
	@-rm -fr build/
	@-rm -fr dist/
	@-rm -fr .eggs/
	@-find . -name '*.egg-info' -exec rm -fr {} +
	@-find . -name '*.egg' -exec rm -f {} +
	@-find . -name '*.log' -exec rm -fr {} +
	@-find . -name '*.sqlite' -exec rm -fr {} +

.PHONY: clean-pyc
clean-pyc:
	@echo "Remove Python file artifacts ..."
	@-find . -name '*.pyc' -exec rm -f {} +
	@-find . -name '*.pyo' -exec rm -f {} +
	@-find . -name '*~' -exec rm -f {} +
	@-find . -name '__pycache__' -exec rm -fr {} +

.PHONY: clean-test
clean-test:
	@echo "Remove test artifacts ..."
	@-rm -fr .pytest_cache

.PHONY: clean-dist
clean-dist: clean
	@echo "Running 'git clean' ..."
	@git diff --quiet HEAD || echo "There are uncommitted changes! Aborting 'git clean' ..."
	## do not use git clean -e/--exclude here, add them to .gitignore instead
	@-git clean -dfx

.PHONY: venv
venv:
	test -d $(VENV) || python3 -m venv $(VENV)

## Test targets

.PHONY: test
test: venv
	@echo "Running tests (skip slow and online tests) ..."
	@bash -c '${PYTHON} -m pytest -v -m "not slow and not online" tests/'

.PHONY: test-all
test-all: venv
	@echo "Running all tests (including slow and online tests) ..."
	@bash -c '${PYTHON} -m pytest -v tests/'

.PHONY: notebook-sanitizer
notebook-sanitizer:
	@echo "Copying notebook output sanitizer ..."
	@-bash -c "curl -L $(SANITIZE_FILE) -o $(CURDIR)/docs/output-sanitize.cfg --silent"

.PHONY: test-notebooks
test-notebooks: notebook-sanitizer
	@echo "Running notebook-based tests"
	@bash -c "source $(VENV)/bin/activate && env LOCAL_URL=$(LOCAL_URL) pytest --nbval --verbose $(CURDIR)/notebooks/ --sanitize-with $(CURDIR)/output-sanitize.cfg --ignore $(CURDIR)/notebooks/.ipynb_checkpoints"

.PHONY: test-notebooks-prod
test-notebooks-prod: notebook-sanitizer
	@echo "Running notebook-based tests against production instance of osprey"
	@bash -c "source $(VENV)/bin/activate && pytest --nbval --verbose $(CURDIR)/notebooks/ --sanitize-with $(CURDIR)/output-sanitize.cfg --ignore $(CURDIR)/notebooks/.ipynb_checkpoints"

.PHONY: test-notebooks-dev
test-notebooks-dev: notebook-sanitizer
	@echo "Running notebook-based tests against development instance of osprey"
	@bash -c "source $(VENV)/bin/activate && env DEV_URL=http://docker-dev03.pcic.uvic.ca:30100/wps pytest --nbval --verbose $(CURDIR)/notebooks/ --sanitize-with $(CURDIR)/output-sanitize.cfg --ignore $(CURDIR)/notebooks/.ipynb_checkpoints"

.PHONY: test-notebooks-custom
test-notebooks-custom: notebook-sanitizer
	@echo "Running notebook-based tests against custom instance of osprey"
	@bash -c "source $(VENV)/bin/activate && env DEV_URL=http://docker-dev03.pcic.uvic.ca:$(DEV_PORT)/wps pytest --nbval --verbose $(CURDIR)/notebooks/ --sanitize-with $(CURDIR)/output-sanitize.cfg --ignore $(CURDIR)/notebooks/.ipynb_checkpoints"

.PHONY: lint
lint: venv
	@echo "Running black code style checks ..."
	@bash -c '${PYTHON} -m black . --check'

.PHONY: refresh-notebooks
refresh-notebooks:
	@echo "Refresh all notebook outputs under notebooks"
	@bash -c 'for nb in $(CURDIR)/notebooks/*.ipynb; do LOCAL_URL="$(LOCAL_URL)" jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=60 --output "$$nb" "$$nb"; sed -i "s@$(LOCAL_URL)/outputs/@$(OUTPUT_URL)/@g" "$$nb"; done; cd $(APP_ROOT)'

## Documentation

.PHONY: docs
docs:
	@echo "Updating notebook docs"
	@bash -c 'source $(VENV)/bin/activate && jupyter nbconvert --to html notebooks/* --output-dir docs/formatted_demos/'

## Deployment targets

.PHONY: dist
dist: clean
	@echo "Building source and wheel package ..."
	@-python setup.py sdist
	@-python setup.py bdist_wheel
	@-bash -c 'ls -l dist/'
