version: '3.4'

services:
  osprey-dev:
    image: ${OSPREY_DEV_IMAGE}
    container_name: osprey-dev
    environment:
      - PYWPS_CFG=/wps.cfg
    ports:
      - "30100:5000"
    volumes:
      - ../../osprey/pavics-component/wps.cfg:/wps.cfg
      - wps_outputs:/data/wpsoutputs
      - /tmp
    restart: always

  magpie:
    volumes:
    - ../../osprey/pavics-component/osprey-magpie-permission.cfg:/opt/local/src/magpie/config/permissions/osprey-magpie-permission.cfg:ro
    - ../../osprey/pavics-component/osprey-magpie-provider.cfg:/opt/local/src/magpie/config/providers/osprey-magpie-provider.cfg:ro

  proxy:
    volumes:
      - ../../osprey/pavics-component/osprey_canarie_api_monitoring.py:${CANARIE_MONITORING_EXTRA_CONF_DIR}/osprey_canarie_api_monitoring.py:ro