name: Anchore Container Scan
on:
  push:
    branches:
      - master
      - '*security*'
      - '*vulnerability*'

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - name: Run the Anchore scan
      uses: anchore/scan-action@main
      with:
        image: "localbuild/testimage:latest"
        acs-report-enable: true
        severity-cutoff: high
    - name: Upload Anchore Scan Report
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
