name: Docker Image Scan

on:
  push:
    branches:
      - master
      - '*security*'

jobs:
  scan:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --file Dockerfile --tag pcic/osprey:test-image
    - uses: anchore/scan-action@v1
      with:
        image-reference: "pcic/osprey:test-image"
        fail-build: true
    - name: Upload Report
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AnchoreReports
        path: ./anchore-reports/
