name: Python CI

on: push

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry lock
          poetry install --extras "dev"
      - name: Test with pytest (full)
        if: github.ref == 'refs/heads/master'
        run: |
          poetry run py.test -m "not online" -v
      - name: Test with pytest (fast)
        if: github.ref != 'refs/heads/master'
        run: |
          poetry run py.test -m "not online and not slow" -v
